import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import BackgroundImgMobileMain from "../assets/home/background-home-mobile.jpg";
import NavBar from "../components/navbar";
import TempNavBar from "../components/tempnavbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image
          className={styles.backgroundImage}
          src={BackgroundImgMobileMain}
          alt="Picture of the author"
          layout="fill"
          objectFit="cover"
          quality={100}
        />

        <NavBar />
        <div className={styles.home__content}>
          <div className={styles.home__title1}>So, you want to travel to</div>
          <div className={styles.home__title2}> SPACE</div>
          <div className={styles.home__description}>
            Let’s face it. if you want to go to space, you might as well
            genuinely go to outer space and not hover kind of on the edge of it.
            Well sit back, and relax because we’ll give you a truly out of this
            world experience!
          </div>

          <div className={styles.home__explorebtn}> EXPLORE</div>
        </div>
      </main>
      <TempNavBar />
    </div>
  );
}
